name: Angular Project Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: docker build . --file Dockerfile --tag lassoya/enora-front:latest
      - name: publish
        run: |
          docker login -u winnux82 -p ${{ secrets.DOCKER_HUB_PWD }}
          docker push wnx82/githubangular:latest
  deploy_image:
    needs: build_image
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@v2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            docker login -u winnux82 -p ${{ secrets.DOCKER_HUB_PWD }}
            docker pull wnx82/githubangular:latest
            docker stop githubangular
            docker rm githubangular
            docker run -d \
            -p 8080:80 \
            --name githubangular wnx82/githubangular:latest
